### ISSUE TITLE
Manual adding up

### ISSUE THREAD

**Issue by Ooglely** [Ooglely/pugBot#40]
Allow players to manually add up to pugs, and ping all players once a player threshold has been reached.

In theory this would add:
- /pug setup(?), set up manual pugs (ex. player threshold)
- /add #, add up to pugs for a specific amount of hours. 
- /missing, ping everyone who added who is still not in the VC
- /status, see who is currently added (and maybe add this in the topic of a channel too?)
- /clear, clear the add up list

#29 will be connected to this

- [x] Setup/Database
- [x] Add/Remove
- [x] Missing
- [x] Status
- [x] Clear player/all
- [x] Change channel topic to pug status

**Comment by blakeplusplus** [comment]
- Doing just /add should add you up to a set default time. Maybe server configurable? Good default would be 2-4 hours.
- Someone adding up should output a message to chat with the updated count. Helps get pugs running if people see constant activity in the command channel for adding up.
- /clear <player> should clear a specific player from the list. Sometimes users will bait.

Once the max player threshold for pugs has been reached, the bot should automatically balance teams and spit out a message to the add up command text channel. Since pugs have pretty low player counts, we usually let players directly see the teams, so having them be able to immediately go in their respective team VC would be good.
